on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm classroom run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "ecowatch_classroom"
          path: ${{ github.workspace }}/packages/classroom/dist/*
