on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm -r -F classroom -F student -F teacher run build

      - name: Upload classroom artifact
        uses: actions/upload-artifact@v4
        with:
          name: "ecowatch_classroom"
          path: ${{ github.workspace }}/packages/classroom/dist/*

      - name: Upload student artifact
        uses: actions/upload-artifact@v4
        with:
          name: "ecowatch_student"
          path: ${{ github.workspace }}/packages/student/dist/*

      - name: Upload teacher artifact
        uses: actions/upload-artifact@v4
        with:
          name: "ecowatch_teacher"
          path: ${{ github.workspace }}/packages/teacher/dist/*
