on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm -r -F classroom -F student -F teacher run build

      - name: Upload classroom artifact
        uses: actions/upload-artifact@v4
        with:
          name: "ecowatch_classroom"
          path: ${{ github.workspace }}/packages/classroom/dist/*

      - name: Upload student artifact
        uses: actions/upload-artifact@v4
        with:
          name: "ecowatch_student"
          path: ${{ github.workspace }}/packages/student/dist/*

      - name: Upload teacher artifact
        uses: actions/upload-artifact@v4
        with:
          name: "ecowatch_teacher"
          path: ${{ github.workspace }}/packages/teacher/dist/*

  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith( github.ref, 'refs/tags/' )

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Zip artifacts
        run: |
          cd ./artifacts
          zip -r ecowatch_classroom.zip ecowatch_classroom
          zip -r ecowatch_student.zip ecowatch_student
          zip -r ecowatch_teacher.zip ecowatch_teacher

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./artifacts/ecowatch_classroom.zip,
            ./artifacts/ecowatch_student.zip,
            ./artifacts/ecowatch_teacher.zip"
          makeLatest: "latest"
